# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Custom chain
chain = "ethersocial"
# Blockchain and settings will be stored in ~/.local/share/io.parity.ethersocial.
base_path = "$HOME/.local/share/io.parity.ethersocial"

[network]
discovery = true
# Parity will listen for connections on port 50505.
port = 50505
# Parity will try to maintain connection to at least 30 peers.
min_peers = 30
# Parity will maintain at most 60 peers.
max_peers = 60
reserved_only = false
# Specify a path to a file with peers' enodes to be always connected to.
reserved_peers = "./reserved_peers"

[rpc]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
# Allows Cross-Origin Requests from domain '*'.
cors = ["*"]
# Allow connections only using specified addresses.
hosts = ["all"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts"]
# Threads for handling incoming connections for HTTP JSON-RPC server.
server_threads = 16
# Turn on additional processing threads in all RPC servers. Setting this to non-zero value allows parallel cpu-heavy queries execution.
processing_threads = 16

[mining]
author = "0xe3ec5ebd3e822c972d802a0ee4e0ec080b8237ba"

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Increase performance on SSD.
db_compaction = "ssd"
# Keep all state trie data. No pruning.
pruning = "archive"
# Enables Fat DB
fat_db = "on"

[snapshots]
disable_periodic = true

[misc]
color = true
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
#logging = "discovery=trace"